### ISSUE TITLE
Fix Math markdown rendering issues in Astro Day 24

### ISSUE THREAD

**Issue by dalurness** [dalurness/winter-code-fest#11]
Day 24 has a good amount of math going on. It is written in markdown, but Astro is not currently rendering it as expected. I believe you can install a plugin to Astro for the markdown rendering in order to fix it. Depending on the plugin, we might need to rewrite the question a bit to fit the plugin's expected syntax.

How it should look:
![image](https://github.com/user-attachments/assets/b6184264-3b4c-48d3-8826-59eef4513f98)

How it currently looks:
![image](https://github.com/user-attachments/assets/8a5afc30-abc5-4394-a5f1-40f47ffd2c83)

**Comment by janka102** [comment]
Taking a look...
